import { useState } from "react";
import { Link } from "wouter";
import ProductShell from "@/components/ProductShell";
import { chipProducts, metrologyRules } from "@/data/catalog";

export function RulesPage() { const [selected, setSelected] = useState(chipProducts[0].id); const product = chipProducts.find(item => item.id === selected) ?? chipProducts[0]; const [checks, setChecks] = useState(product.rules); return <ProductShell><div className="route-page"><PageTitle eyebrow="EVIDENCE CHECKLIST" title="10-rule metrology check" text="Compare every required declaration against the selected company reference value." /><div className="product-picker">{chipProducts.map(item => <button className={item.id === selected ? "active" : ""} onClick={() => { setSelected(item.id); setChecks(item.rules); }} key={item.id}>{item.brand}</button>)}</div><div className="rule-page-summary"><strong>{checks.filter(Boolean).length}/10</strong><span>rules checked · {product.brand} demo reference</span></div><div className="route-rule-list">{metrologyRules.map(([code, title, detail], index) => <label className={checks[index] ? "checked" : ""} key={code}><input type="checkbox" checked={checks[index]} onChange={event => setChecks(current => current.map((value, i) => i === index ? event.target.checked : value))} /><b>{checks[index] ? "✓" : ""}</b><span><strong>{code} · {title}</strong><small>{detail}</small><em>{[product.manufacturer, product.origin, product.product, product.declared, product.mfgDate, product.bestBefore, product.mrp, product.usp, product.consumerCare, product.barcode][index]}</em></span></label>)}</div><Link href="/verdicts" className="button button-dark">Continue to verdict ↗</Link></div></ProductShell>; }

export function VerdictsPage() { const [selected, setSelected] = useState(chipProducts[0].id); const product = chipProducts.find(item => item.id === selected) ?? chipProducts[0]; return <ProductShell><div className="route-page"><PageTitle eyebrow="INSPECTION OUTCOME" title="Verdicts" text="See the compliance outcome and the evidence behind the selected package profile." /><div className="product-picker">{chipProducts.map(item => <button className={item.id === selected ? "active" : ""} onClick={() => setSelected(item.id)} key={item.id}>{item.brand}</button>)}</div><div className={`large-verdict ${product.verdict === "COMPLIANT" ? "pass" : "review"}`}><span>{product.verdict}</span><strong>{product.score}<small>/100 match score</small></strong><p>{product.verdict === "COMPLIANT" ? "All seeded demo declarations satisfy the reference checklist." : "Review the highlighted product risks and confirm all package evidence before approval."}</p></div><div className="evidence-grid"><div><span>Declared / measured</span><strong>{product.declared} / {product.measured}</strong></div><div><span>MRP / unit sale</span><strong>{product.mrp} / {product.usp}</strong></div><div><span>Manufacturer</span><strong>{product.manufacturer}</strong></div><div><span>Barcode</span><strong>{product.barcode}</strong></div></div><section className="inner-section"><h2>Ingredients</h2><div className="ingredient-pills">{product.ingredients.map(item => <span key={item}>{item}</span>)}</div></section><Link href="/health" className="button button-line">Review allergens and health ↗</Link></div></ProductShell>; }

export function HealthPage() { const [selected, setSelected] = useState(chipProducts[0].id); const product = chipProducts.find(item => item.id === selected) ?? chipProducts[0]; return <ProductShell><div className="route-page"><PageTitle eyebrow="FSSAI REG. 2.4.5" title="Health & allergen review" text="Separate declared ingredients, allergen signals, and health-risk advisories from the legal-metrology verdict." /><div className="product-picker">{chipProducts.map(item => <button className={item.id === selected ? "active" : ""} onClick={() => setSelected(item.id)} key={item.id}>{item.brand}</button>)}</div><section className="health-banner"><span>ALLERGEN DECLARATION</span><strong>{product.allergens.join(" · ")}</strong></section><div className="health-layout"><div><h2>Ingredient read</h2><div className="ingredient-table route-ingredients">{product.ingredients.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong><em>{/salt|oil|sugar|palm/i.test(item) ? "HEALTH SIGNAL" : /milk|soy/i.test(item) ? "ALLERGEN" : "DECLARED"}</em></div>)}</div></div><div><h2>Risk advisories</h2>{product.risks.map(risk => <div className="risk-card" key={risk.name}><div><strong>{risk.name}</strong><span className={risk.level}>{risk.level.toUpperCase()}</span></div><i><b className={risk.level} style={{ width: `${risk.score}%` }} /></i><p>{risk.reason}</p></div>)}</div></div></div></ProductShell>; }

function PageTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="route-title"><div><span className="section-kicker">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></div>; }
