import { useEffect, useRef, useState } from "react";
import { Link } from "wouter";
import ProductShell from "@/components/ProductShell";
import { chipProducts, ChipProduct } from "@/data/catalog";

const panels = ["Front PDP", "Back PDP", "Ingredients panel", "Barcode / batch side"];
export default function Scanner() {
  const [brand, setBrand] = useState(chipProducts[0].id); const [frames, setFrames] = useState<string[]>([]); const [open, setOpen] = useState(false); const [status, setStatus] = useState("ready"); const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null);
  const product = chipProducts.find(item => item.id === brand) ?? chipProducts[0];
  useEffect(() => () => streamRef.current?.getTracks().forEach(track => track.stop()), []);
  async function openCamera() { setOpen(true); try { streamRef.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); if (videoRef.current) videoRef.current.srcObject = streamRef.current; } catch { setStatus("camera permission needed"); } }
  function closeCamera() { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; setOpen(false); }
  function capture() { if (frames.length >= 4) return; setFrames(current => [...current, panels[current.length]]); setStatus(`${frames.length + 1}/4 captured`); }
  function runScan() { setStatus("processing"); window.setTimeout(() => { const record = { id: `${Date.now()}`, brandId: product.id, brand: product.brand, product: product.product, verdict: product.verdict, score: product.score, scannedAt: new Date().toISOString(), panels: frames.length }; const history = JSON.parse(localStorage.getItem("metrology-history") ?? "[]"); localStorage.setItem("metrology-history", JSON.stringify([record, ...history].slice(0, 50))); setStatus("10-rule verdict ready"); closeCamera(); }, 700); }
  return <ProductShell><div className="route-page scanner-page"><div className="route-title"><div><span className="section-kicker">PRIMARY INSPECTION WORKFLOW</span><h1>Scan package</h1><p>Capture four views. Extract evidence. Review ten metrology rules.</p></div><Link href="/history" className="button button-line">Scan history ↗</Link></div><div className="scan-command"><div><span className="eyebrow">Selected fallback profile</span><select value={brand} onChange={event => setBrand(event.target.value)}>{chipProducts.map(item => <option value={item.id} key={item.id}>{item.brand} · {item.product}</option>)}</select><p className="muted">Used only when OCR cannot confidently identify the company profile.</p></div><div className="scan-meter"><strong>{frames.length}/4</strong><span>panels captured</span><i><b style={{ width: `${frames.length * 25}%` }} /></i><small>{status}</small></div><button className="button button-dark" onClick={openCamera}>{open ? "Camera open" : "Start camera scan"}</button></div><div className="panel-grid">{panels.map((panel, index) => <div className={frames[index] ? "panel-card captured" : "panel-card"} key={panel}><b>0{index + 1}</b><strong>{panel}</strong><span>{frames[index] ? "FRAME READY" : index === 0 ? "Product, quantity, MRP" : index === 1 ? "Manufacturer, dates, care" : index === 2 ? "Ingredients and allergens" : "Barcode, batch, lot"}</span></div>)}</div>{open && <div className="camera-workspace"><div className="camera-viewport"><video ref={videoRef} autoPlay playsInline muted /><div className="camera-crop" /><span>Align {panels[frames.length] ?? panels[3]}</span></div><div className="camera-controls"><h2>Build inspection dossier</h2><p>Use even light. Keep the selected panel flat and readable.</p><div className="capture-actions"><button className="button button-line" onClick={closeCamera}>Close</button><button className="button button-line" onClick={capture} disabled={frames.length >= 4}>Capture {panels[frames.length] ?? "complete"}</button><button className="button button-dark" onClick={runScan} disabled={frames.length === 0 || status === "processing"}>Run 10-rule scan</button></div></div></div>}<div className="scan-next"><Link href="/rules" className="button button-line">Review rules</Link><Link href="/verdicts" className="button button-dark">Open verdicts</Link></div></div></ProductShell>;
}
