import { FormEvent, useEffect, useState } from "react";
import ProductShell from "@/components/ProductShell";
import { chipProducts, metrologyRules } from "@/data/catalog";

export function HistoryPage() { const [items, setItems] = useState<Array<{ id: string; brand: string; product: string; verdict: string; score: number; scannedAt: string; panels: number }>>([]); useEffect(() => setItems(JSON.parse(localStorage.getItem("metrology-history") ?? "[]")), []); return <ProductShell><div className="route-page"><div className="route-title"><div><span className="section-kicker">INSPECTION TRAIL</span><h1>Scan history</h1><p>Stored local inspection records for products scanned on this device.</p></div><button className="button button-line" onClick={() => { localStorage.removeItem("metrology-history"); setItems([]); }}>Clear history</button></div><div className="history-list">{items.length === 0 ? <div className="empty-state"><strong>No scans stored yet.</strong><span>Start a package scan and your inspection record will appear here.</span></div> : items.map(item => <article key={item.id}><div><span>{new Date(item.scannedAt).toLocaleString()}</span><h2>{item.brand}</h2><p>{item.product} · {item.panels}/4 panels captured</p></div><strong className={item.verdict === "COMPLIANT" ? "pass-text" : "review-text"}>{item.verdict}<small>{item.score}/100</small></strong></article>)}</div></div></ProductShell>; }

export function ModesPage() { const initialMode = typeof window !== "undefined" && new URLSearchParams(window.location.search).get("mode") === "company" ? "company" : typeof window !== "undefined" && new URLSearchParams(window.location.search).get("mode") === "admin" ? "admin" : "officer"; const [mode, setMode] = useState<"admin" | "officer" | "company">(initialMode); return <ProductShell><div className="route-page"><div className="route-title"><div><span className="section-kicker">ROLE-BASED WORKSPACE</span><h1>Choose your mode</h1><p>Use the same inspection evidence with a workspace designed for your responsibility.</p></div></div><div className="mode-tabs">{([["officer", "Consumer / Officer"], ["company", "Company"], ["admin", "Admin"]] as const).map(([id, label]) => <button className={mode === id ? "active" : ""} onClick={() => setMode(id)} key={id}>{label}</button>)}</div>{mode === "officer" && <div className="workspace-card"><span className="eyebrow">FIELD INSPECTION</span><h2>Scan, verify, explain.</h2><p>Open the camera scanner, review all ten rules, then inspect the verdict and health pages.</p><div className="route-actions"><a className="button button-dark" href="/scan">Open scanner</a><a className="button button-line" href="/history">View history</a></div></div>}{mode === "company" && <CompanyWorkspace />}{mode === "admin" && <AdminWorkspace />}</div></ProductShell>; }

function CompanyWorkspace() { const [selected, setSelected] = useState(chipProducts[0].id); const product = chipProducts.find(item => item.id === selected) ?? chipProducts[0]; const failed = product.rules.map((pass, index) => pass ? null : metrologyRules[index]).filter(Boolean); return <div className="workspace-card company-workspace"><span className="eyebrow">COMPANY SELF-CHECK</span><h2>Where does your package fall short?</h2><select value={selected} onChange={e => setSelected(e.target.value)}>{chipProducts.map(item => <option value={item.id} key={item.id}>{item.brand} · {item.product}</option>)}</select><div className="company-score"><strong>{failed.length}</strong><span>rules currently flagged in this reference profile</span></div>{failed.length === 0 ? <p className="pass-text">All ten reference rules are currently satisfied. Upload verified company data before treating this as a formal assessment.</p> : <div className="failure-list">{failed.map(rule => rule && <div key={rule[0]}><strong>{rule[0]} · {rule[1]}</strong><span>{rule[2]}</span></div>)}</div>}<p className="muted">This is a demo company workspace. Official conclusions require verified product data and statutory review.</p></div>; }

function AdminWorkspace() { const [selected, setSelected] = useState(chipProducts[0].id); const [field, setField] = useState("mrp"); const [value, setValue] = useState(chipProducts[0].mrp); const [saved, setSaved] = useState(""); const submit = async (event: FormEvent) => { event.preventDefault(); const response = await fetch(`/api/chips/catalog/${selected}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ [field]: value }) }); const result = await response.json(); setSaved(result.persistence === "database" ? "Amendment saved to the product catalog database." : "Amendment saved."); }; return <div className="workspace-card"><span className="eyebrow">CATALOG ADMINISTRATION</span><h2>Amend product reference data</h2><p>Edit a company reference field used by rules and comparisons.</p><form className="admin-form" onSubmit={submit}><select value={selected} onChange={e => setSelected(e.target.value)}>{chipProducts.map(item => <option value={item.id} key={item.id}>{item.brand}</option>)}</select><select value={field} onChange={e => setField(e.target.value)}><option value="mrp">MRP</option><option value="bestBefore">Best-before</option><option value="consumerCare">Consumer care</option><option value="manufacturer">Manufacturer</option></select><input value={value} onChange={e => setValue(e.target.value)} placeholder="New reference value" /><button className="button button-dark">Save amendment</button></form>{saved && <p className="pass-text">{saved}</p>}<p className="muted">Every amendment is stored in the product catalog database. Add authenticated roles and an audit log before production use.</p></div>; }
